#openapi: 3.0.0
#info:
#  title: Sukify API
#  description: API for client-side, hi again molbert
#  version: 0.1.9
#
#servers:
#  - url: http://localhost:8000/api
#    description: local server
#  - url: http://producation.app/api
#    description: production server
#
#paths:
#  /users:
#    get:
#      summary: Returns a list of users.
#      responses:
#        '200':
#          description: A JSON array of user names
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  type: string
swagger: "2.0"
info:
  version: 1.0.5
  title: API Documentation
host: 4807-176-52-96-170.ngrok-free.app
basePath: /method
tags: [ ]
paths:

  /api/tracks/search:
    get:
      tags:
        - Tracks
      summary: Get tracks
      description: <b>In work</b>
      operationId: tracks
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: search
          type: string
          description: search by
      responses:
        "200":
          description: OK
          examples:
            application/json: {
              "data": [
                {
                  "id": 58,
                  "name": "Ломай меня полностью (Hard Dubstep Remix)",
                  "release_date": "2001-12-11T00:00:00.000000Z",
                  "counter": 0,
                  "cover_file": "https://4807-176-52-96-170.ngrok-free.app/storage/images202301/S1eaWxcNecnAgkXFnZC1ayNmZBOVmIcBt8m31SDx.png",
                  "file": "https://4807-176-52-96-170.ngrok-free.app/storage/music202301/QaSuhZVLFYT9y7YIZWeC0ErWMbcQ8IOj77nxOPaw.mp3",
                  "video_file": "http://localhost:8000/storage/videos202301/4x0dkHxFqAlTjkz4TdSMkWAEHLvn13KbqOsGeTaM.png",
                  "is_fav": false,
                  "artists": [
                    {
                      "id": 25,
                      "name": "AContrari",
                      "avatar": null,
                      "background": null,
                      "pivot": {
                        "track_id": 58,
                        "artist_id": 25
                      }
                    }
                  ]
                },
                {
                  "id": 57,
                  "name": "Im Hunting Wabbits Dubstep",
                  "release_date": "2002-02-02T00:00:00.000000Z",
                  "counter": 0,
                  "cover_file": "https://4807-176-52-96-170.ngrok-free.app/storage/images202301/1ELqhICVNIFvhnpNKHfVMP9xwS7IY4xsxItzHKyk.png",
                  "file": "https://4807-176-52-96-170.ngrok-free.app/storage/music202301/xZQDNys6OgVUnMD5urbodviM68XfH9tmh2OR73bt.mp3",
                  "video_file": "http://localhost:8000/storage/videos202301/PX0qtWC0lDBasfr2k8dQ89pidjSnUn282Hjqlt0X.png",
                  "is_fav": true,
                  "artists": [
                    {
                      "id": 26,
                      "name": "Looney Tunes",
                      "avatar": null,
                      "background": null,
                      "pivot": {
                        "track_id": 57,
                        "artist_id": 26
                      }
                    }
                  ]
                }
              ],
              "path": "http://localhost/api/tracks/search",
              "per_page": 5,
              "next_cursor": "eyJjb3VudGVyIjowLCJpZCI6NTQsIl9wb2ludHNUb05leHRJdGVtcyI6dHJ1ZX0",
              "next_page_url": "http://localhost/api/tracks/search?cursor=eyJjb3VudGVyIjowLCJpZCI6NTQsIl9wb2ludHNUb05leHRJdGVtcyI6dHJ1ZX0",
              "prev_cursor": null,
              "prev_page_url": null
            }